added-snyk-ignore-policy for egress and ingress
sourcefuse/terraform-aws-ref-arch-network pull request #20
Opened 2022-11-18 10:04 UTC by mayank0202

2022-12-03 02:01 UTC, tsaucier-sf commented
* When you open a PR, please be sure you run `pre-commit run -a`. 
* Please run `tflint .` in the root of the repo and resolve the warnings.

2022-12-03 02:02 UTC, tsaucier-sf requested changes
Please run `tflint .` in the root of the repo and resolve the warnings, I didn't have a change to fix them.

2023-01-06 16:30 UTC, jamescrowley321 approved these changes

2023-01-06 17:02 UTC, tsaucier-sf approved these changes

2023-01-06 17:43 UTC, merged