chore: cleanup-docs
sourcefuse/terraform-aws-ref-arch-network pull request #29
Opened 2023-01-23 19:24 UTC by jamescrowley321

2023-01-23 19:51 UTC, mayank0202 submitted a review, later dismissed

2023-01-24 17:36 UTC, tsaucier-sf requested changes

2023-01-24 17:36 UTC, tsaucier-sf commented on LICENSE
> +   Copyright 2017-2020 Cloud Posse, LLC
Should this be changed to `Copyright 2022 SourceFuse` like the other modules?

2023-01-25 03:55 UTC, tsaucier-sf approved these changes

2023-01-25 13:53 UTC, mayank0202 approved these changes

2023-01-25 13:53 UTC, shubhamsinha-sf approved these changes

2023-01-25 13:53 UTC, merged

2023-01-25 13:57 UTC, tsaucier-sf approved these changes