github action to copy readme files to arc-docs
sourcefuse/terraform-aws-ref-arch-network pull request #36
Opened 2023-03-23 07:34 UTC by saurabhjindal-SF

2023-03-24 19:32 UTC, mayank0202 requested changes

2023-03-24 19:32 UTC, mayank0202 commented on .github/workflows/update-docs.yml
> +          API_TOKEN_GITHUB: ${{ secrets.ARC_DOCS_TOKEN }}
`GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`

2023-03-24 19:32 UTC, mayank0202 commented on .github/workflows/update-docs.yml
> +          user_email: 'saurabh.jindal@gmail.com'
Please modify this to use the PR author's info.

2023-03-24 19:32 UTC, mayank0202 commented on .github/workflows/update-docs.yml
> +          user-email: saurabh.jindal@gmail.com
Please modify this to use the PR author's info.

2023-03-24 19:32 UTC, mayank0202 commented on .github/workflows/update-docs.yml
> +          user-email: saurabh.jindal@gmail.com
Please modify this to use the PR author's info.

2023-03-24 19:32 UTC, mayank0202 commented on .version
> +2.1.6
give `2.1.7`

2023-03-25 22:14 UTC, mayank0202 approved these changes

2023-03-26 15:43 UTC, jamescrowley321 approved these changes

2023-03-26 15:43 UTC, merged